### ISSUE TITLE
Block Scalars not properly retrieved

### ISSUE THREAD

**Issue by Alaith** [mikefarah/yaml#104]
Retrieving a block scalar causes the Block Style Indicator along with extra indentation to be returned. Ideally, the utility should know how to properly interpret Block Scalars per the yaml spec
http://www.yaml.org/spec/1.2/spec.html#id2795688

Current Behavior:
```
$ yaml r - test << EOF
test: |
  abcdefg
  hijklmno
EOF
|
  abcdefg
  hijklmno
```

Expected Behavior:
```
$ yaml r - test << EOF
test: |
  abcdefg
  hijklmno
EOF
abcdefg
hijklmno
```

I'm not sure if this is a limitation of go-yaml or not, but if not it would be great if you could incorporate this part of the yaml spec.

**Comment by kenjones-cisco** [comment]
The value is being properly interpreted based on Yaml spec. And it does find the value:
` 
abcdefg
hijklmno
`
Once the value is found, and then converted into Yaml as output then go-yaml will convert the string back into a block scalar.

The reason being is to avoid losing the formatted associated with block scalar like indention and new lines.

When adding the `-j` to the command, the response comes back as `"abcdefg\nhijklmno\n"`.

I believe what you are looking for is the ability to get the output value to be "raw" which means no Yaml encoding. Which is a feature that is not currently supported. But in alignment with jq, that could be a feature that could be added.

**Comment by Alaith** [comment]
Apologies, I misinterpreted the function of the `r` command. Thank you for your comment to clear that up.

I would like a "raw" output option, but for now I can leverage other utilities.

Thanks again.

**Comment by mikefarah** [comment]
I've been thinking about this a little more seeing it comes up often - I think it does make more (practical) sense to print out the multiline string instead of the block scalar.

Fixed in https://github.com/mikefarah/yq/releases/tag/1.14.1
