### ISSUE TITLE
Can't read files that consist of a string or a sequence

### ISSUE THREAD

**Issue by ianmackinnon** [mikefarah/yaml#13]
The following two examples don't seem to work for me on Linux using version 1.11.

    $ echo 'alphabet' | yaml r -
    [error parsing data:  yaml: unmarshal errors:
      line 1: cannot unmarshal !!str `alphabet` into yaml.MapSlice]

    $ echo -e '- alpha\n- beta' | yaml r -
    [error parsing data:  yaml: unmarshal errors:
      line 1: cannot unmarshal !!str `alpha` into yaml.MapItem
      line 2: cannot unmarshal !!str `beta` into yaml.MapItem]

**Comment by mikefarah** [comment]
Bummer - didn't think of yaml files that didn't have a map as the root object. I'll look into it

**Comment by mikefarah** [comment]
Fixed! 
https://github.com/mikefarah/yaml/releases/tag/1.12
