### ISSUE TITLE
Can't handle multiple yaml documents within one file

### ISSUE THREAD

**Issue by Godley** [mikefarah/yaml#16]
Say I have:
```
---
mykey: myvalue
---
mykey: myothervalue
---
mykey: myotherothervalue
```
I'd expect the tool to be able to handle all three documents and give me a list of values when I run
`yaml r myfile.yaml mykey`, instead it'd just give me the first value.

Is this something you'd be willing to add as a feature? Happy to work on it myself but I have limited go knowledge.

**Comment by mikefarah** [comment]
Yep this is a known issue with the yaml library I'm using https://github.com/mikefarah/yaml/issues/9

**Comment by Godley** [comment]
ah, apologies for the duplication!

**Comment by mikefarah** [comment]
All good - the title on #9 isn't very clear now that I think of it, I'm going to use yours.

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/144

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/147#

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/pull/137
