### ISSUE TITLE
push to exist array structure

### ISSUE THREAD

**Issue by davidkhala** [mikefarah/yaml#17]
In my case, I have to write yaml arrays to file in this way

```
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[0] a
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[1] b  
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[2] c  
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[3] d  
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[4] e  
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[5] f  
    yaml w -i $COMPOSE_FILE services.$peerContainer.environment[6] g  
```
which manually input index is clumsy. script file option might help, but I do not like to use this method 
Is there any plan to support new feature like that
`yaml w -i --append $COMPOSE_FILE services.$peerContainer.environment[]  newValPush2end `

**Comment by mikefarah** [comment]
Yeah totally agree, that would be neat 👍 

I'm time poor atm - but would def accept a feature request

**Comment by brianreese** [comment]
Is there an analog to this feature in 4.x?
