### ISSUE TITLE
Can't write Array

### ISSUE THREAD

**Issue by l89669** [mikefarah/yaml#3]
Build a config.yml like this:
 `test:`
`- aa`

When I use `yaml r config.yml test[0]` , it output `aa`.
When I use `yaml w -i config.yml test[0] bb` , it gives this error.

>  panic: interface conversion: interface {} is []interface {}, not map[interface {}]interface {}
> 
> goroutine 1 [running]:
> panic(0x665980, 0xc820070780)
>         /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
> main.write(0xc820076f90, 0x7ffc1e8d26be, 0x4, 0xc82006fbd0, 0x1, 0x1, 0x5fe200, 0xc820074b20)
>         /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/data_navigator.go:13 +0x261
> main.updateYaml(0xc820076cf0, 0x3, 0x3, 0x0, 0x0)
>         /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:122 +0x278
> main.writeProperty(0xc82010c1e0, 0xc820076cf0, 0x3, 0x3)
>         /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:98 +0x4a
> github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra.(_Command).execute(0xc82010c1e0, 0xc820076b70, 0x3, 0x3, 0x0, 0x0)
>         /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x85a
> github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra.(_Command).Execute(0xc82010c3c0, 0x0, 0x0)
> /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x46a
> main.main()
>        /Users/mikefarah/dev/go/src/github.com/mikefarah/yaml/yaml.go:29 +0x36d

So is this an issue or  I'm using wrong way to write Array?

**Comment by l89669** [comment]
I've find a temp solution. but that is a bit complex because it needs nodejs to be installed first. I'll keep on watching this repo to see if this bug could be fixed : )

**Comment by mikefarah** [comment]
I've fixed this issue with the latest release (1.5). Let me know if there are any issues :)

**Comment by mikefarah** [comment]
Also, sorry it took so long
