### ISSUE TITLE
Update YAML file with the new key

### ISSUE THREAD

**Issue by Trane9991** [mikefarah/yaml#7]
Given a sample.yaml file of:
```
b:
  c: 2
```
then

`yaml w -i sample.yaml b.d cat`

Expected result:
```
b:
  c: 2
  d: cat
```

**Comment by mikefarah** [comment]
cool, on it.

I think i'll be able to extend the fix to be able to create yaml from scratch.. 🤔

**Comment by Trane9991** [comment]
Yeah, that would be really awesome!

**Comment by mikefarah** [comment]
I'll get the fix out for your issue fix, and work on creating a 'new'
command or something that creates a new yaml using the same syntax as the
write command.

**Comment by mikefarah** [comment]
Fixed in 1.7, let me know if there are any issues :)
